[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
ETH_SEPOLIA_RPC_URL="https://eth-sepolia.g.alchemy.com/v2/mcWIzodsxxgJ-gG8HXOJR"

ARB_SEPOLIA_RPC_URL="https://arb-sepolia.g.alchemy.com/v2/mcWIzodsxxgJ-gG8HXOJR"

BASE_SEPOLIA_RPC_URL="https://base-sepolia.g.alchemy.com/v2/mcWIzodsxxgJ-gG8HXOJR"