[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
ETH_SEPOLIA_RPC_URL="https://sepolia.infura.io/v3/ea2422e0e27a48ee82964d0dea2be9e8"

ARB_SEPOLIA_RPC_URL="https://arb-sepolia.g.alchemy.com/v2/bwlhh2eGj0MA1bXE6h31Z"

BASE_SEPOLIA_RPC_URL="https://base-sepolia.infura.io/v3/ea2422e0e27a48ee82964d0dea2be9e8"