name: CI -> build & push -> trigger Render
on:
  push:
    branches: [ main ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_ACCESS_TOKEN }}

      - name: Install monorepo deps
        run: npm install --frozen-lockfile
        working-directory: ./apps/frontend

      - name: Build web app
        run: npm run build
        working-directory: ./apps/frontend

      - name: Build and push image
        env:
         NEXT_PUBLIC_ALCHEMY_ID: ${{ secrets.NEXT_PUBLIC_ALCHEMY_ID }}
         NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID }}
         PAT_ACCESS_TOKEN: ${{secrets.PAT_ACCESS_TOKEN}}
        uses: docker/build-push-action@v4
        with:
          context: ./apps/frontend
          file: ./apps/frontend/Dockerfile
          push: true
          tags: ghcr.io/luftjunkie19/stabilski-nextjs-app:latest

      - name: Trigger Render deploy
        run: |
          curl -X POST -sS https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{}'